# Generated by Django 5.2.1 on 2025-05-16 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_foto',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
